name: textvault

services:
  app:
    container_name: app-textvault
    build:
      context: .
      target: app
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"


  flyway:
    build:
      context: .
      target: flyway
    environment:
      FLYWAY_URL: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DB}?allowPublicKeyRetrieval=true&useSSL=false
      FLYWAY_USER: ${MYSQL_USER}
      FLYWAY_PASSWORD: ${MYSQL_PASSWORD}
      FLYWAY_VALIDATE_MIGRATION_NAMING: "true"
    command: migrate
    extra_hosts:
    - "host.docker.internal:host-gateway"